name: Python package

on:
  push:
  pull_request:
  schedule:
    - cron: "0 10 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: nikeee/setup-pandoc@v1
    - name: download README.md
      run: make README.md -B
    - name: Commit changes
      run: |
        if ! git diff --exit-code; then
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'ickc@users.noreply.github.com'
          git commit -am "Automated commit"
          git push
        fi
